### ISSUE TITLE
Can't 

### ISSUE THREAD

**Issue by zhangfusheng-163** [kennymckormick/pyskl#34] opened 2022-05-23 07:46 UTC
When I run /tools/data/custom_2d_skeleton.py,there has a problem
File "tools/data/custom_2d_skeleton.py", line 176, in <module>
    main()
  File "tools/data/custom_2d_skeleton.py", line 123, in main
    init_dist('pytorch', backend='nccl')
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

 I can't find RANK from "os.environ['RANK']",so I change 'LOCAL_RANK' to 'RANK',but there has other problem，about that:
File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 224, in _env_rendezvous_handler
    world_size = int(_get_env_or_raise("WORLD_SIZE"))
  File "/home/xunlong/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 203, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable WORLD_SIZE expected, but not set

who solved this question,please give some advises，Thank you very much!

**Comment by kennymckormick** [comment] 2022-05-24 06:35
Duplicate of #35

**Closed by kennymckormick** 2022-05-24 06:35 UTC
