### ISSUE TITLE
where are configs of RGB+Pose?

### ISSUE THREAD

**Issue by 2000ZRL** [kennymckormick/pyskl#8] opened 2022-04-24 06:56 UTC
I am sorry that I cannot find configs of RGB+Pose models that there should be two paths. But in configs/posec3d I can only find configs that only take pose as inputs, i.e., one path, the input channel is 17. Could you help me with that? Thanks.

**Comment by kennymckormick** [comment] 2022-04-24 08:07
Currently that is not released, I will release it in the future.

**Comment by kennymckormick** [comment] 2022-04-29 12:27
Duplicate of #1

**Closed by kennymckormick** 2022-04-29 12:27 UTC
